# Generated by Django 4.2.4 on 2023-08-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firsttask', '0003_rename_retail_id_dispatch_retail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='conact',
            new_name='contact',
        ),
    ]
