# Generated by Django 4.2.4 on 2023-08-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttask', '0005_remove_dispatch_contact_dispatch_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='sent',
            field=models.BooleanField(default=True),
        ),
    ]
