# Generated by Django 4.2.4 on 2023-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttask', '0007_alter_dispatch_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
